name: Lint HTML and CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Comprobar el código
      - name: Check out code
        uses: actions/checkout@v2

      # 2. Instalar herramientas para validar HTML y CSS
      - name: Install HTML and CSS Linters
        run: |
          sudo apt-get install -y tidy
          npm install -g stylelint

      # 3. Verificar instalación de tidy
      - name: Verificar instalación de tidy
        run: tidy --version

      # 4. Verificar instalación de stylelint
      - name: Verificar instalación de stylelint
        run: stylelint --version

      # 5. Validar HTML
      - name: Lint HTML
        run: tidy -e "3.2. Sitio Web sencillo/index.html"

      # 6. Validar CSS
      - name: Lint CSS
        run: stylelint "3.2. Sitio Web sencillo/styles.css"
