name: Lint HTML and CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Comprobar el código
      - name: Check out code
        uses: actions/checkout@v2

      # 2. Instalar herramientas para validar HTML y CSS
      - name: Install HTML and CSS Linters
        run: |
          sudo apt-get install -y tidy
          npm install -g stylelint

      # 3. Validar HTML (validará el archivo index.html dentro de la carpeta '3.2. Sitio Web sencillo')
      - name: Lint HTML
        run: tidy -qe "3.2. Sitio Web sencillo/index.html" || true

      # 4. Validar CSS (validará el archivo styles.css dentro de la carpeta '3.2. Sitio Web sencillo')
      - name: Lint CSS
        run: stylelint "3.2. Sitio Web sencillo/styles.css"
